version: '2'

services:
  db:
    build:
      context: .
      dockerfile: ./db/Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=raspisms

  raspisms:
    build:
      context: .
      dockerfile: ./raspisms/Dockerfile
    depends_on:
      - db
    ports:
      - "80:80"
    volumes:
      - gammu:/var/spool/gammu/
      - receiveds:/var/www/html/RaspiSMS/receiveds

  gammu:
    build:
      context: .
      dockerfile: ./gammu/Dockerfile
    devices:
      - /dev/ttyUSB0:/dev/mobile
    volumes:
      - gammu:/var/spool/gammu/
      - receiveds:/var/www/html/RaspiSMS/receiveds

  jobber:
    build: ./jobber
    depends_on:
      - raspisms
    labels:
      - "io.balena.features.balena-socket=true"

volumes:
  gammu: ~
  receiveds: ~
