version: '2.1'

services:
  db:
    build:
      context: .
      dockerfile: ./db/Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=raspisms
    # healthcheck:
    #   test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
    #   interval: 5s
    #   timeout: 30s
    #   retries: 10
    volumes:
      - db:/var/config/databases

  directus:
    build: ./directus
    depends_on:
      - directus_installer
    environment:
      - DIRECTUS_AUTH_PUBLICKEY=11223344
      - DIRECTUS_AUTH_SECRETKEY=55667788
      - DIRECTUS_DATABASE_HOST=db
      - DIRECTUS_DATABASE_NAME=raspisms
      - DIRECTUS_DATABASE_USERNAME=root
      - DIRECTUS_DATABASE_PASSWORD=root
    labels:
      - "traefik.enable=true"
      # https://github.com/directus/api/issues/636
      - "traefik.http.routers.directus.rule=PathPrefix(`/`)"
      - "traefik.http.routers.directus.entrypoints=web"

  directus_installer:
    build: ./directus
    command:
      - install
    depends_on:
      - db
      # db:
      #   condition: service_healthy
    environment:
      - DIRECTUS_AUTH_PUBLICKEY=11223344
      - DIRECTUS_AUTH_SECRETKEY=55667788
      - DIRECTUS_DATABASE_HOST=db
      - DIRECTUS_DATABASE_USERNAME=root
      - DIRECTUS_DATABASE_PASSWORD=root
      - DIRECTUS_DATABASE_NAME=raspisms
      - DIRECTUS_INSTALL_PASSWORD=admin
    restart: "no"

  gammu:
    build:
      context: .
      dockerfile: ./gammu/Dockerfile
    devices:
      - /dev/ttyUSB0:/dev/mobile
      # - /dev/null:/dev/mobile
    volumes:
      - gammu:/var/spool/gammu/
      - receiveds:/var/www/html/raspisms/receiveds

  raspisms:
    build:
      context: .
      dockerfile: ./raspisms/Dockerfile
    depends_on:
      - db
      - gammu
      # db:
      #   condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.raspisms.rule=PathPrefix(`/raspisms`)"
      - "traefik.http.routers.raspisms.entrypoints=web"
    volumes:
      - gammu:/var/spool/gammu/
      - receiveds:/var/www/html/raspisms/receiveds

  cron:
    build: ./cron
    depends_on:
      - raspisms
    labels:
      - "io.balena.features.balena-socket=true"
    # volumes:
    #   - /var/run/docker.sock:/var/run/docker.sock:ro

  traefik:
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.endpoint=unix:///var/run/balena.sock"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    # traefik:v2.2.0
    image: traefik@sha256:6d0a99e202bc3f732000a78b696281369b771234893fff22106471f3d65daffb
    labels:
      - "io.balena.features.balena-socket=true"
    ports:
      - "80:80"
      - "8080:8080"
    # volumes:
    #   - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  db: ~
  gammu: ~
  receiveds: ~
