FROM mariadb@sha256:90c426bf71d2d375f6056bae573c5b7fc38fe85ad6befcb509baa37ef39d5eef

# COPY ./raspisms/createDatabase.sql /docker-entrypoint-initdb.d/00_raspisms_createDatabase.sql
# COPY ./db/insertAdminUser.sql /docker-entrypoint-initdb.d/10_raspisms_insertAdminUser.sql

# COPY ./tusci/snapshot_20200714.sql /docker-entrypoint-initdb.d/00_tusci.sql
